
ClassStrategyCO = {};
ClassStrategyNC = {};

function InitializeStrategy()
	ClassStrategyCO = {
[1] = {"grind","autonomous activity","When there is no target in the battle, the robot will find the target within the field of view and attack."},
[2] = {"attack weak","Free attack","The robot will freely choose the target to attack during the battle."},
[3] = {"attack force","passive attack","The robot will not choose a target during combat, you must manually specify the attack target."},
[4] = {"tank","Pull a single monster","The robot only holds one monster alone. After killing it, it will pull the next one."},
[5] = {"tank aoe","Pull multiple monsters","All monsters in the battle are targets for the robot to pull."},
[6] = {"tank assist","tank assist","The robot assists in attacking the current target of the tank character in the team."},
[7] = {"dps","Single DPS","The robot only outputs one monster alone. After killing it, it outputs the next monster."},
[8] = {"dps aoe","group AOE","When there are many monsters in the battle, the robot will use AOE skills to output."},
[9] = {"dps assist","DPS assist","Robots assist in destroying monsters in the team."},
[10] = {"dps debuff","damage BUFF","The robot will cast a continuous damage BUFF on the target during combat."},
[11] = {"heal","Heal teammates","The robot will heal injured teammates during the battle and will no longer output DPS."},
[12] = {"aoe","group attack","Robots will use group damage skills in combat."},
[13] = {"flee","distance","When the robot is close to its current target in combat, it will try to run away."},
[14] = {"fire","Fire spell","Robots use fire spells to output targets during combat. (For mage robots)"},
[15] = {"fire aoe","fire AOE","When there are many monsters in the battle, the robot will use fire AOE spell output. (For mage robots)"},
[16] = {"frost","Frost Spell","Robots use frost spells to output targets during combat. (For mage robots)"},
[17] = {"frost aoe","frost AOE","When there are many monsters in the battle, the robot will use the frost AOE spell output. (Aimed at the mage robot)"},
[18] = {"arcane","Arcane Spell","Robots use arcane spells to output targets during combat. (For mage robots)"},
[19] = {"threat","hate control","The robot will output conservatively during battle to prevent OT."},
[20] = {"conserve mana","Energy Control","The robot will use its own mana sparingly and reduce its output capacity during combat."},
[21] = {"shadow","Shadow Spell","Robots use shadow spells to output output to targets during combat. (For Warlock and Priest robots)"},
[22] = {"shadow aoe","shadow AOE","When there are many monsters in the battle, the robot will use the shadow AOE spell output. (For warlocks and priest robots)"},
[23] = {"shadow debuff","Shadow damage BUFF","The robot will cast shadow continuous damage BUFF on the target during combat. (For Warlock and Priest robots)"},
[24] = {"melee","Close combat","Robots always attack close to the target during combat. (For Shaman robots)"},
[25] = {"melee aoe","Close group attack","Robots approach the target to perform group attacks during combat. (Aimed at shaman robots)"},
[26] = {"rshadow","Shadow Resistance Aura","The robot turns on the Shadow Resistance Aura during combat. (For Paladin robots)"},
[27] = {"rfrost","Frost Resistance Aura","The robot turns on the Frost Resistance Aura during combat. (For Paladin robots)"},
[28] = {"rfire","Fire resistance aura","The robot turns on the fire resistance aura during combat. (For Paladin robots)"},
[29] = {"barmor","Armor Defense Aura","The robot turns on the Armor Defense Aura during battle. (For Paladin robots)"},
[30] = {"bspeed","Mount Speed Aura","The robot turns on the mount speed aura during battle. (For Paladin robots)"},
[31] = {"rnature","Natural Resistance Aura","The robot turns on the Natural Resistance Aura during combat. (For hunter robots)"},
[32] = {"bhealth","Life BUFF","The robot provides a health BUFF for itself and its teammates during battle."},
[33] = {"bmana","Auxiliary BUFF","The robot provides auxiliary BUFF for itself and its teammates during battle."},
[34] = {"bdps","Offensive BUFF","Robots gain offensive BUFF for themselves and teammates during battle."},
[35] = {"bear","Bear and giant bear form","The robot transforms into a bear during battle to perform DPS output. (For Druid robots)"},
[36] = {"cat","Cheetah form","The robot transforms into a cheetah during battle to perform DPS output. (For Druid robots)"},
[37] = {"cat aoe","Cheetah group attack","The robot transforms into a cheetah during the battle and performs group output. (Aimed at Druid robots)"},
[38] = {"caster","Remote spell output","Robots use remote spells to output in combat. (For Druid and Shaman robots)"},
[39] = {"caster aoe","Remote group spell","When there are many monsters in the battle, the robot uses remote AOE spells for output. (For Druid and Shaman robots)"},
[40] = {"caster debuff","Remote damage BUFF","The robot will cast a long-range continuous damage BUFF on the target during combat. (For Druid and Shaman robots)"},
[41] = {"totems","totem","Robots will place some totems around them during battle. (For shaman robots)"},
[42] = {"loot","pickup","The robot will pick up and drop the corpses around it during the battle."},
[43] = {"naxx","Naxxramas","The robot's behavior will be targeted at the Naxxramas instance. (Only valid in the Naxxramas instance)"},
	};

	ClassStrategyNC = {
[1] = {"grind","autonomous activity","When not in combat, the robot looks for targets within the field of view to attack."},
[2] = {"move random","Move randomly","When not in combat, the robot will run randomly when it is bored."},
[3] = {"attack weak","free attack","When not in combat, the robot can freely choose the target to attack when it enters combat."},
[4] = {"attack force","passive attack","When not in combat, the robot will not perform any attacks, and you must manually specify the attack target."},
[5] = {"bhealth","Life BUFF","When not in combat, the robot will give itself and its teammates a BUFF that increases the life."},
[6] = {"bmana","Auxiliary BUFF","When not in combat, the robot will apply auxiliary BUFF to itself and its teammates."},
[7] = {"bdps","Offensive BUFF","When not in combat, the robot will apply offensive BUFF to itself and its teammates."},
[8] = {"emote","expression","When not in combat, the robot will make some emoticons from time to time when it is bored."},
[9] = {"food","rest","After leaving the battle, the robot will give itself water and bread according to the situation."},
[10] = {"loot","pickup","After leaving the battle, the robot will pick up the surrounding corpses and drop them."},
[11] = {"stay","stay","When not in combat, the robot will stand still."},
[12] = {"follow","follow","When not in combat, the robot follows the player."},
[13] = {"quest","mission","When not in combat, the robot will accept and complete tasks for the NPC the player is currently interacting with."},
[14] = {"naxx","Naxxramas","The robot's behavior will be targeted at the Naxxramas instance. (Only valid in the Naxxramas instance)"},
	};
end
